version: '3.4'

services:

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_TCP_PORT=1433
    ports:
      - 1433:1433
  